spring:
  application:
    name: studentapi
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/studendb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true